Remove --setup
Running the command from the example with the `--setup` flag ends up in an error for me:
```
./filebeat -e -strict.perms=false -E output.elasticsearch.hosts=["es01:9200"] --modules=apache2 --setup -M "apache2.access.var.paths=['./apache_logs']"
Error: unknown command "apache2.access.var.paths=['./apache_logs']" for "filebeat"
Run 'filebeat --help' for usage.
```
Removing `--setup` works fine.
Since I can't find the `--setup` documented somewhere in the [latest docs of the filebeat cli](https://www.elastic.co/guide/en/beats/filebeat/current/command-line-options.html#run-command) I assume it was replaced by the `setup` command and is therefore deprecated in this example.